version: '3.8'
services:
  app:
    build: .
    ports:
      - 8000:4000
    environment:
      PORT: 4000
      DB_URL: 'mongodb://mongo:27017'
      DB_NAME: 'car-park'

  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:

networks:
  service:
    driver: bridge